### ISSUE TITLE
Feature Request: Use one source to dinamicly read the modbus slave addresses :-) 

### ISSUE THREAD

**Issue by biovolt** [lucode/home-assistant#1]
Hi Lucas

Thank you for sharing your work!! It really helps me a lot.

May I ask that you use a central place e.g. the secrets file to store the slave addresses and then read it from there so that it is easy to change it for different users where the slave addresses are different? 
This will allow us to easily import new improvements you make.

I know the secrets.yaml is not the best place. Is there a different way to achieve similar functionality to not expose your secrets file?

**Comment by lucode** [comment]
Hi, I'm not quite sure what you have in mind here? As you know all the configuration stuff for modbus is in the modbus.yaml file, including the slave addresses of each entry. I assume you want the to store the different slave numbers outside of the modbus.yaml file and ad a kind of variable which points then to the correct number. But I can't imagine what the benefits would be? Beside of the fact that it is likely technically impossible this way.
In my opinion the only solution which could improve and ease the integration of Victron devices into HA, would be a Victron integration. I think one day someone will get on with this.

**Comment by biovolt** [comment]
Hi
This MR is what I mean and the benefit is:  e.g. My slave values are different from yours, so I need to go through the file and modify them one by one. Now someone needs to edit max 5 values to fix all the slave values.
The Ip address can be done the same way but it is only one value

**Comment by lucode** [comment]
THX @biovolt for the MR, sorry for the late reply, was occupied with other stuff last weeks. Seems very reasonable to do it this way. Haven't yet used secrets.yaml. Always new stuff to learn with HA. Need to ev. update the conf files first and will then merge the MR.
